version: "3.9"

services:
  ml-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    #   - .:/app
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
